"""add shopping_lists table

Revision ID: 5fc28bee67ed
Revises: c131ca8dafdf
Create Date: 2026-05-03 10:08:34.070905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc28bee67ed'
down_revision: Union[str, Sequence[str], None] = 'c131ca8dafdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('diner_count', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_lists')
    # ### end Alembic commands ###
